name: numbertriviaapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Bloc for state management
  flutter_bloc: ^3.2.0
  # For annotations
  meta: ^1.1.8
  # For object comparisons
  equatable: ^1.1.0
  # For functional programming Either<> type
  dartz: ^0.8.9
  # To check for internet connection
  data_connection_checker: ^0.3.4
  # For caching data locally
  shared_preferences: ^0.5.6
  # For making requests to the APIs
  http: ^0.12.0
  # Service Locator for Dependency Injection
  get_it: ^4.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true

