# Name of your workflow.
name: android debug run

# Trigger the workflow on push or pull request.
on: [push, pull_request]

jobs:
    android_debug_run:
        runs-on: macOS-latest
        strategy:
            matrix:
                api-level: [21, 23, 29]
                target: [default, google_apis]
        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Run Android app in Debug Mode
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: ${{ matrix.api-level }}
            target: ${{ matrix.target }}
            arch: x86_64
            profile: Nexus 6
            script: ./scripts/debug-run.sh
